import type { DatabaseState } from '../types';

const now = '2026-04-09T12:00:00.000Z';

function record<T extends { id: string }>(
  value: T,
): T & {
  createdAt: string;
  updatedAt: string;
  deletedAt: null;
} {
  return {
    ...value,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
  };
}

export function createDemoState(): DatabaseState {
  const projectId = '11111111-1111-4111-8111-111111111111';
  const configId = '22222222-2222-4222-8222-222222222222';
  const scriptRunId = '33333333-3333-4333-8333-333333333333';
  const storyboardRunId = '44444444-4444-4444-8444-444444444444';
  const agent1TaskId = '55555555-5555-4555-8555-555555555551';
  const agent2TaskId = '55555555-5555-4555-8555-555555555552';
  const agent3TaskId = '55555555-5555-4555-8555-555555555553';
  const agent4TaskId = '55555555-5555-4555-8555-555555555554';
  const agent6TaskId = '55555555-5555-4555-8555-555555555556';
  const agent7TaskId = '55555555-5555-4555-8555-555555555557';
  const scene1Id = '66666666-6666-4666-8666-666666666661';
  const scene2Id = '66666666-6666-4666-8666-666666666662';
  const shot1Id = '77777777-7777-4777-8777-777777777771';
  const shot2Id = '77777777-7777-4777-8777-777777777772';
  const shot3Id = '77777777-7777-4777-8777-777777777773';
  const storyboardGroup1 = '88888888-8888-4888-8888-888888888881';
  const storyboardGroup2 = '88888888-8888-4888-8888-888888888882';
  const storyboardGroup3 = '88888888-8888-4888-8888-888888888883';
  const videoGroup1 = '99999999-9999-4999-8999-999999999991';
  const videoGroup2 = '99999999-9999-4999-8999-999999999992';
  const videoGroup3 = '99999999-9999-4999-8999-999999999993';
  const keyElementGroup1 = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1';
  const keyElementGroup2 = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2';

  const storyboardVersion1 = 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb1';
  const storyboardVersion2 = 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb2';
  const storyboardVersion3 = 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb3';
  const videoVersion1 = 'cccccccc-cccc-4ccc-8ccc-ccccccccccc1';
  const videoVersion2 = 'cccccccc-cccc-4ccc-8ccc-ccccccccccc2';
  const videoVersion3 = 'cccccccc-cccc-4ccc-8ccc-ccccccccccc3';
  const keyElementVersion1 = 'dddddddd-dddd-4ddd-8ddd-ddddddddddd1';
  const keyElementVersion2 = 'dddddddd-dddd-4ddd-8ddd-ddddddddddd2';

  return {
    projects: [
      record({
        id: projectId,
        title: '西安城市剧情短片',
        userId: null,
        sourceIdea:
          '我想做一个关于西安三日游的剧情感短视频，兼具旅行信息和情绪氛围。',
        targetPlatform: 'douyin',
        language: 'zh-CN',
        status: 'running',
        currentStage: 'storyboard',
        currentConfigVersionId: configId,
        latestRunId: storyboardRunId,
        currentFailureSummaryId: null,
        remark: 'Demo 项目，展示从脚本进入分镜与视频阶段的完整状态。',
      }),
    ],
    projectConfigVersions: [
      record({
        id: configId,
        projectId,
        versionNo: 1,
        confirmedByUser: true,
        sourceTaskId: agent1TaskId,
        scriptType: '混合型',
        styleDefinition: '电影感、轻叙事、城市漫游',
        researchFocus: '城市文化、旅行体验、夜景视觉',
        storylineStructure: '场景卡片式',
        scriptOrganization: '按场景',
        globalConstraints: {
          duration: '45-60s',
          continuity: 'medium',
        },
        configJson: {
          audience: '年轻旅行用户',
          tone: '沉浸、轻戏剧',
        },
        note: '初始确认版本',
        isActive: true,
      }),
    ],
    workflowRuns: [
      record({
        id: scriptRunId,
        projectId,
        workflowType: 'script',
        triggerMode: 'manual',
        startFromNode: 'agent2',
        endAtNode: 'script_user_confirm',
        currentNode: 'script_user_confirm',
        status: 'completed',
        runReason: '完成第一部分脚本工作流',
        retryCount: 0,
        requiresManualReview: false,
        errorType: null,
        errorMessage: null,
        startedAt: now,
        finishedAt: now,
      }),
      record({
        id: storyboardRunId,
        projectId,
        workflowType: 'storyboard',
        triggerMode: 'manual',
        startFromNode: 'agent6',
        endAtNode: 'agent8',
        currentNode: 'agent8',
        status: 'running',
        runReason: '从最终脚本进入第二部分',
        retryCount: 0,
        requiresManualReview: false,
        errorType: null,
        errorMessage: null,
        startedAt: now,
        finishedAt: null,
      }),
    ],
    workflowJobs: [],
    workflowJobAttempts: [],
    agentProfiles: [],
    agentModelBindings: [],
    providerCredentials: [],
    agentPermissions: [],
    agentTasks: [
      record({
        id: agent1TaskId,
        runId: scriptRunId,
        projectId,
        agentName: 'agent1',
        stageName: 'script',
        roundNo: 1,
        parentTaskId: null,
        inputPayload: { sourceIdea: '西安三日游剧情短片' },
        outputJson: {
          projectUnderstanding: '城市旅行叙事，兼顾攻略信息与情绪表达。',
        },
        outputMarkdown:
          '## Agent1 项目理解\n- 目标：做一个兼具旅行信息与剧情感的西安城市短片\n- 风格：电影感、轻叙事、夜景情绪',
        outputSummary: '完成需求理解与配置建议',
        profileVersionId: null,
        modelBindingId: null,
        promptVersion: 'v1',
        status: 'approved',
        errorType: null,
        errorMessage: null,
        latencyMs: 1200,
        promptTokens: 320,
        completionTokens: 280,
        totalTokens: 600,
        startedAt: now,
        finishedAt: now,
      }),
      record({
        id: agent2TaskId,
        runId: scriptRunId,
        projectId,
        agentName: 'agent2',
        stageName: 'script',
        roundNo: 1,
        parentTaskId: null,
        inputPayload: { configVersionId: configId },
        outputJson: {
          facts: ['城墙、钟楼、回民街、大雁塔是典型视觉锚点'],
          marketInsight: ['旅行短视频更偏强代入的个人体验线'],
        },
        outputMarkdown:
          '## 调研摘要\n西安城市内容适合以“古城感 + 夜色 + 情绪漫游”的方式组织，并加入少量旅行信息点作为支撑。',
        outputSummary: '调研完成并通过审核',
        profileVersionId: null,
        modelBindingId: null,
        promptVersion: 'v1',
        status: 'approved',
        errorType: null,
        errorMessage: null,
        latencyMs: 1800,
        promptTokens: 480,
        completionTokens: 620,
        totalTokens: 1100,
        startedAt: now,
        finishedAt: now,
      }),
      record({
        id: agent3TaskId,
        runId: scriptRunId,
        projectId,
        agentName: 'agent3',
        stageName: 'script',
        roundNo: 1,
        parentTaskId: null,
        inputPayload: { basedOnTaskId: agent2TaskId },
        outputJson: {
          scenes: ['抵达古城', '穿行街巷', '夜色收束'],
        },
        outputMarkdown:
          '## 故事线\n1. 抵达城墙建立城市气质\n2. 穿过街巷感受生活肌理\n3. 夜色落在大雁塔，形成情绪收束',
        outputSummary: '故事线完成并通过审核',
        profileVersionId: null,
        modelBindingId: null,
        promptVersion: 'v1',
        status: 'approved',
        errorType: null,
        errorMessage: null,
        latencyMs: 1600,
        promptTokens: 450,
        completionTokens: 500,
        totalTokens: 950,
        startedAt: now,
        finishedAt: now,
      }),
      record({
        id: agent4TaskId,
        runId: scriptRunId,
        projectId,
        agentName: 'agent4',
        stageName: 'script',
        roundNo: 1,
        parentTaskId: null,
        inputPayload: { basedOnTaskId: agent3TaskId },
        outputJson: {
          title: '三天西安，一场带着情绪温度的城市漫游',
        },
        outputMarkdown:
          '## 最终脚本\n黄昏时分，主角拉着行李走向古城墙。镜头切入街巷烟火，再在夜色下收束到大雁塔的静谧光影。',
        outputSummary: '最终脚本已通过审核，等待进入第二部分',
        profileVersionId: null,
        modelBindingId: null,
        promptVersion: 'v1',
        status: 'approved',
        errorType: null,
        errorMessage: null,
        latencyMs: 2200,
        promptTokens: 560,
        completionTokens: 720,
        totalTokens: 1280,
        startedAt: now,
        finishedAt: now,
      }),
      record({
        id: agent6TaskId,
        runId: storyboardRunId,
        projectId,
        agentName: 'agent6',
        stageName: 'storyboard',
        roundNo: 1,
        parentTaskId: null,
        inputPayload: { scriptTaskId: agent4TaskId },
        outputJson: {
          sceneCount: 2,
          shotCount: 3,
        },
        outputMarkdown:
          '## Shot 抽取\n共抽取 2 个场景、3 个 shot，覆盖抵达、穿行、夜景收束三段关键画面。',
        outputSummary: 'shot 拆分完成并通过审核',
        profileVersionId: null,
        modelBindingId: null,
        promptVersion: 'v1',
        status: 'approved',
        errorType: null,
        errorMessage: null,
        latencyMs: 1500,
        promptTokens: 400,
        completionTokens: 520,
        totalTokens: 920,
        startedAt: now,
        finishedAt: now,
      }),
      record({
        id: agent7TaskId,
        runId: storyboardRunId,
        projectId,
        agentName: 'agent7',
        stageName: 'storyboard',
        roundNo: 1,
        parentTaskId: null,
        inputPayload: { basedOnTaskId: agent6TaskId },
        outputJson: {
          enrichedShots: 3,
        },
        outputMarkdown:
          '## Shot 扩写\n补充光线、氛围、动作和镜头衔接信息，可直接支撑 Agent8 生成关键分镜图。',
        outputSummary: 'shot 扩写完成并通过审核',
        profileVersionId: null,
        modelBindingId: null,
        promptVersion: 'v1',
        status: 'approved',
        errorType: null,
        errorMessage: null,
        latencyMs: 1700,
        promptTokens: 420,
        completionTokens: 610,
        totalTokens: 1030,
        startedAt: now,
        finishedAt: now,
      }),
    ],
    reviewRecords: [
      record({
        id: 'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeee1',
        projectId,
        runId: scriptRunId,
        sourceTaskId: agent2TaskId,
        reviewerType: 'agent',
        reviewerName: 'agent5',
        decision: 'pass',
        reviewStyle: 'balanced',
        score: 86,
        failedRules: [],
        feedbackMarkdown: '调研有事实基础，且能为后续故事线提供稳定依据。',
        revisionBrief: null,
        reviewRound: 1,
        isFinal: true,
      }),
      record({
        id: 'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeee2',
        projectId,
        runId: scriptRunId,
        sourceTaskId: agent3TaskId,
        reviewerType: 'agent',
        reviewerName: 'agent5',
        decision: 'pass',
        reviewStyle: 'balanced',
        score: 84,
        failedRules: [],
        feedbackMarkdown: '故事线与调研承接关系清晰，可支撑脚本展开。',
        revisionBrief: null,
        reviewRound: 1,
        isFinal: true,
      }),
      record({
        id: 'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeee3',
        projectId,
        runId: scriptRunId,
        sourceTaskId: agent4TaskId,
        reviewerType: 'agent',
        reviewerName: 'agent5',
        decision: 'pass',
        reviewStyle: 'balanced',
        score: 88,
        failedRules: [],
        feedbackMarkdown: '脚本结构完整，风格与前置要求一致。',
        revisionBrief: null,
        reviewRound: 1,
        isFinal: true,
      }),
    ],
    projectStageSnapshots: [
      record({
        id: 'f1f1f1f1-f1f1-4f1f-8f1f-f1f1f1f1f1f1',
        projectId,
        stageName: 'script',
        sourceTaskId: agent4TaskId,
        sourceArtifactVersionId: null,
        snapshotJson: {
          title: '三天西安，一场带着情绪温度的城市漫游',
        },
        snapshotMarkdown:
          '黄昏抵达古城墙，穿行烟火街巷，最终在夜色中将情绪沉淀到大雁塔。',
        isActive: true,
      }),
    ],
    failureSummaryDocs: [],
    scenes: [
      record({
        id: scene1Id,
        projectId,
        sourceTaskId: agent6TaskId,
        sceneIndex: 1,
        title: '抵达古城',
        scriptSegment: '主角抵达古城墙，建立西安的第一印象。',
        sceneDesc: '黄昏暖色下的古城墙与旅人背影。',
        status: 'active',
        note: null,
      }),
      record({
        id: scene2Id,
        projectId,
        sourceTaskId: agent6TaskId,
        sceneIndex: 2,
        title: '夜色收束',
        scriptSegment: '夜色中，大雁塔成为整个旅程的情绪锚点。',
        sceneDesc: '蓝金色夜景，节奏从热闹回落到安静。',
        status: 'active',
        note: null,
      }),
    ],
    shots: [
      record({
        id: shot1Id,
        projectId,
        sceneId: scene1Id,
        sourceTaskId: agent6TaskId,
        shotIndexGlobal: 1,
        shotIndexInScene: 1,
        title: '城墙远景建立',
        scriptSegment: '主角拉着行李走向城墙。',
        sceneDesc: '黄昏、广阔城墙、城市初见感。',
        subjectDesc: '旅人背影与城墙轮廓',
        actionDesc: '缓步走近镜头前景',
        moodDesc: '期待、安静、沉浸',
        continuityNotes: '下一镜切到街巷近景，节奏略快。',
        status: 'active',
        isUserAdded: false,
        sortVersion: 1,
        note: null,
      }),
      record({
        id: shot2Id,
        projectId,
        sceneId: scene1Id,
        sourceTaskId: agent6TaskId,
        shotIndexGlobal: 2,
        shotIndexInScene: 2,
        title: '街巷生活掠影',
        scriptSegment: '镜头穿过热闹街巷，烟火感出现。',
        sceneDesc: '热闹街道，灯笼和人群形成动态层次。',
        subjectDesc: '街巷摊位与行走主角',
        actionDesc: '手持跟拍，轻微横移',
        moodDesc: '温热、鲜活、贴近生活',
        continuityNotes: '下一镜转向夜景远景，需要保留主角服装和风格连续性。',
        status: 'active',
        isUserAdded: false,
        sortVersion: 1,
        note: null,
      }),
      record({
        id: shot3Id,
        projectId,
        sceneId: scene2Id,
        sourceTaskId: agent6TaskId,
        shotIndexGlobal: 3,
        shotIndexInScene: 1,
        title: '大雁塔夜色收束',
        scriptSegment: '大雁塔在夜色里成为旅程的静谧落点。',
        sceneDesc: '蓝金色夜景、广场水面反光、节奏放缓。',
        subjectDesc: '大雁塔与主角停驻背影',
        actionDesc: '镜头缓慢推进，人物停下回望',
        moodDesc: '宁静、回味、留恋',
        continuityNotes: '收束镜头，可作为视频结尾或转字幕。',
        status: 'active',
        isUserAdded: false,
        sortVersion: 1,
        note: null,
      }),
    ],
    artifactGroups: [
      record({
        id: storyboardGroup1,
        projectId,
        scopeType: 'shot',
        scopeId: shot1Id,
        artifactType: 'image',
        role: 'storyboard_image',
        name: 'Shot 1 关键分镜',
        activeVersionId: storyboardVersion1,
        status: 'active',
        isUserManaged: true,
        note: null,
      }),
      record({
        id: storyboardGroup2,
        projectId,
        scopeType: 'shot',
        scopeId: shot2Id,
        artifactType: 'image',
        role: 'storyboard_image',
        name: 'Shot 2 关键分镜',
        activeVersionId: storyboardVersion2,
        status: 'active',
        isUserManaged: true,
        note: null,
      }),
      record({
        id: storyboardGroup3,
        projectId,
        scopeType: 'shot',
        scopeId: shot3Id,
        artifactType: 'image',
        role: 'storyboard_image',
        name: 'Shot 3 关键分镜',
        activeVersionId: storyboardVersion3,
        status: 'active',
        isUserManaged: true,
        note: null,
      }),
      record({
        id: videoGroup1,
        projectId,
        scopeType: 'shot',
        scopeId: shot1Id,
        artifactType: 'video',
        role: 'video_clip',
        name: 'Shot 1 视频片段',
        activeVersionId: videoVersion1,
        status: 'active',
        isUserManaged: true,
        note: null,
      }),
      record({
        id: videoGroup2,
        projectId,
        scopeType: 'shot',
        scopeId: shot2Id,
        artifactType: 'video',
        role: 'video_clip',
        name: 'Shot 2 视频片段',
        activeVersionId: videoVersion2,
        status: 'active',
        isUserManaged: true,
        note: null,
      }),
      record({
        id: videoGroup3,
        projectId,
        scopeType: 'shot',
        scopeId: shot3Id,
        artifactType: 'video',
        role: 'video_clip',
        name: 'Shot 3 视频片段',
        activeVersionId: videoVersion3,
        status: 'active',
        isUserManaged: true,
        note: '当前为占位版本',
      }),
      record({
        id: keyElementGroup1,
        projectId,
        scopeType: 'project',
        scopeId: projectId,
        artifactType: 'image',
        role: 'character_ref',
        name: '主角设定图',
        activeVersionId: keyElementVersion1,
        status: 'active',
        isUserManaged: true,
        note: null,
      }),
      record({
        id: keyElementGroup2,
        projectId,
        scopeType: 'project',
        scopeId: projectId,
        artifactType: 'image',
        role: 'style_ref',
        name: '夜景风格参考图',
        activeVersionId: keyElementVersion2,
        status: 'active',
        isUserManaged: true,
        note: null,
      }),
    ],
    artifactVersions: [
      record({
        id: storyboardVersion1,
        groupId: storyboardGroup1,
        versionNo: 1,
        generatedByAgent: 'agent8',
        sourceTaskId: agent7TaskId,
        mimeType: 'image/jpeg',
        storageBucket: 'mock',
        storagePath: 'storyboards/shot-1.jpg',
        publicUrl:
          'https://placehold.co/800x450/e0b15f/1f1f1f?text=Shot+1+Storyboard',
        fileSizeBytes: 102400,
        width: 800,
        height: 450,
        durationMs: null,
        generationInput: {},
        metadata: {},
        status: 'generated',
        versionNote: '初版分镜图',
        isPlaceholder: false,
      }),
      record({
        id: storyboardVersion2,
        groupId: storyboardGroup2,
        versionNo: 1,
        generatedByAgent: 'agent8',
        sourceTaskId: agent7TaskId,
        mimeType: 'image/jpeg',
        storageBucket: 'mock',
        storagePath: 'storyboards/shot-2.jpg',
        publicUrl:
          'https://placehold.co/800x450/c7653a/ffffff?text=Shot+2+Storyboard',
        fileSizeBytes: 102400,
        width: 800,
        height: 450,
        durationMs: null,
        generationInput: {},
        metadata: {},
        status: 'generated',
        versionNote: '街巷版本',
        isPlaceholder: false,
      }),
      record({
        id: storyboardVersion3,
        groupId: storyboardGroup3,
        versionNo: 1,
        generatedByAgent: 'agent8',
        sourceTaskId: agent7TaskId,
        mimeType: 'image/jpeg',
        storageBucket: 'mock',
        storagePath: 'storyboards/shot-3.jpg',
        publicUrl:
          'https://placehold.co/800x450/1c3862/ffffff?text=Shot+3+Storyboard',
        fileSizeBytes: 102400,
        width: 800,
        height: 450,
        durationMs: null,
        generationInput: {},
        metadata: {},
        status: 'generated',
        versionNote: '夜景收束版本',
        isPlaceholder: false,
      }),
      record({
        id: videoVersion1,
        groupId: videoGroup1,
        versionNo: 1,
        generatedByAgent: 'agent9',
        sourceTaskId: null,
        mimeType: 'video/mp4',
        storageBucket: 'mock',
        storagePath: 'videos/shot-1.mp4',
        publicUrl: 'https://samplelib.com/lib/preview/mp4/sample-5s.mp4',
        fileSizeBytes: 2100000,
        width: 1280,
        height: 720,
        durationMs: 4100,
        generationInput: {},
        metadata: {},
        status: 'approved',
        versionNote: '稳定建立镜头',
        isPlaceholder: false,
      }),
      record({
        id: videoVersion2,
        groupId: videoGroup2,
        versionNo: 1,
        generatedByAgent: 'agent9',
        sourceTaskId: null,
        mimeType: 'video/mp4',
        storageBucket: 'mock',
        storagePath: 'videos/shot-2.mp4',
        publicUrl: 'https://samplelib.com/lib/preview/mp4/sample-5s.mp4',
        fileSizeBytes: 2200000,
        width: 1280,
        height: 720,
        durationMs: 3800,
        generationInput: {},
        metadata: {},
        status: 'generated',
        versionNote: '街巷动态版本',
        isPlaceholder: false,
      }),
      record({
        id: videoVersion3,
        groupId: videoGroup3,
        versionNo: 1,
        generatedByAgent: 'agent9',
        sourceTaskId: null,
        mimeType: 'video/mp4',
        storageBucket: 'mock',
        storagePath: 'videos/shot-3-placeholder.mp4',
        publicUrl:
          'https://placehold.co/1280x720/111111/f4f0e8?text=Placeholder+Clip',
        fileSizeBytes: 4096,
        width: 1280,
        height: 720,
        durationMs: 3000,
        generationInput: {},
        metadata: {
          reason: 'video_generation_failed',
        },
        status: 'placeholder',
        versionNote: '失败后自动占位版本',
        isPlaceholder: true,
      }),
      record({
        id: keyElementVersion1,
        groupId: keyElementGroup1,
        versionNo: 1,
        generatedByAgent: 'agent8',
        sourceTaskId: agent7TaskId,
        mimeType: 'image/jpeg',
        storageBucket: 'mock',
        storagePath: 'elements/main-character.jpg',
        publicUrl:
          'https://placehold.co/512x768/8b6b4a/ffffff?text=Character+Ref',
        fileSizeBytes: 78200,
        width: 512,
        height: 768,
        durationMs: null,
        generationInput: {},
        metadata: {},
        status: 'approved',
        versionNote: '主角衣着设定',
        isPlaceholder: false,
      }),
      record({
        id: keyElementVersion2,
        groupId: keyElementGroup2,
        versionNo: 1,
        generatedByAgent: 'agent8',
        sourceTaskId: agent7TaskId,
        mimeType: 'image/jpeg',
        storageBucket: 'mock',
        storagePath: 'elements/night-style.jpg',
        publicUrl:
          'https://placehold.co/512x768/1f2f4c/ffffff?text=Night+Style',
        fileSizeBytes: 78200,
        width: 512,
        height: 768,
        durationMs: null,
        generationInput: {},
        metadata: {},
        status: 'approved',
        versionNote: '夜景光效参考',
        isPlaceholder: false,
      }),
    ],
    shotAssetBindings: [
      record({
        id: 'abababab-abab-4bab-8bab-ababababab01',
        projectId,
        shotId: shot1Id,
        artifactGroupId: storyboardGroup1,
        bindingRole: 'storyboard_main',
        isPrimary: true,
        influenceScope: 'current_shot',
        note: null,
      }),
      record({
        id: 'abababab-abab-4bab-8bab-ababababab02',
        projectId,
        shotId: shot2Id,
        artifactGroupId: storyboardGroup2,
        bindingRole: 'storyboard_main',
        isPrimary: true,
        influenceScope: 'current_shot',
        note: null,
      }),
      record({
        id: 'abababab-abab-4bab-8bab-ababababab03',
        projectId,
        shotId: shot3Id,
        artifactGroupId: storyboardGroup3,
        bindingRole: 'storyboard_main',
        isPrimary: true,
        influenceScope: 'current_shot',
        note: null,
      }),
      record({
        id: 'abababab-abab-4bab-8bab-ababababab04',
        projectId,
        shotId: shot1Id,
        artifactGroupId: videoGroup1,
        bindingRole: 'video_main',
        isPrimary: true,
        influenceScope: 'current_shot',
        note: null,
      }),
      record({
        id: 'abababab-abab-4bab-8bab-ababababab05',
        projectId,
        shotId: shot2Id,
        artifactGroupId: videoGroup2,
        bindingRole: 'video_main',
        isPrimary: true,
        influenceScope: 'current_shot',
        note: null,
      }),
      record({
        id: 'abababab-abab-4bab-8bab-ababababab06',
        projectId,
        shotId: shot3Id,
        artifactGroupId: videoGroup3,
        bindingRole: 'video_main',
        isPrimary: true,
        influenceScope: 'current_shot',
        note: null,
      }),
      record({
        id: 'abababab-abab-4bab-8bab-ababababab07',
        projectId,
        shotId: shot1Id,
        artifactGroupId: keyElementGroup1,
        bindingRole: 'character_ref',
        isPrimary: true,
        influenceScope: 'referenced_shots',
        note: null,
      }),
      record({
        id: 'abababab-abab-4bab-8bab-ababababab08',
        projectId,
        shotId: shot2Id,
        artifactGroupId: keyElementGroup2,
        bindingRole: 'style_ref',
        isPrimary: true,
        influenceScope: 'referenced_shots',
        note: null,
      }),
    ],
    objectLocks: [
      record({
        id: '12121212-1212-4212-8212-121212121212',
        projectId,
        objectType: 'shot',
        objectId: shot1Id,
        lockScope: 'cascade',
        cascadeChildren: [storyboardVersion1, videoVersion1],
        lockedByUserId: null,
        lockReason: '用户确认首镜已稳定',
        isActive: true,
      }),
    ],
    userAnnotations: [],
    taskEvents: [
      record({
        id: '13131313-1313-4313-8313-131313131310',
        projectId,
        runId: scriptRunId,
        taskId: agent4TaskId,
        eventType: 'manual_gate_confirmed',
        eventLevel: 'info',
        userVisible: true,
        summary: '最终脚本已由用户确认，可以进入 Shot 制作阶段',
        eventPayload: {
          node: 'script_user_confirm',
          confirmedAt: now,
          scriptTaskId: agent4TaskId,
        },
      }),
      record({
        id: '13131313-1313-4313-8313-131313131311',
        projectId,
        runId: storyboardRunId,
        taskId: agent6TaskId,
        eventType: 'task_finished',
        eventLevel: 'info',
        userVisible: true,
        summary: 'Agent6 已完成 shot 抽取',
        eventPayload: {},
      }),
      record({
        id: '13131313-1313-4313-8313-131313131312',
        projectId,
        runId: storyboardRunId,
        taskId: agent7TaskId,
        eventType: 'task_finished',
        eventLevel: 'info',
        userVisible: true,
        summary: 'Agent7 已完成 shot 扩写',
        eventPayload: {},
      }),
      record({
        id: '13131313-1313-4313-8313-131313131313',
        projectId,
        runId: storyboardRunId,
        taskId: null,
        eventType: 'user_alert',
        eventLevel: 'warn',
        userVisible: true,
        summary: 'Shot 3 视频当前为占位片段，请补充素材或重新生成。',
        eventPayload: {
          shotId: shot3Id,
        },
      }),
    ],
    outboxEvents: [
      record({
        id: '14141414-1414-4414-8414-141414141410',
        aggregateType: 'workflow_run',
        aggregateId: scriptRunId,
        eventType: 'manual_gate_confirmed',
        eventPayload: {
          projectId,
          runId: scriptRunId,
          taskId: agent4TaskId,
          node: 'script_user_confirm',
          confirmedAt: now,
          userEventId: '13131313-1313-4313-8313-131313131310',
        },
        publishedAt: null,
        publishAttempts: 0,
        lastError: null,
      }),
    ],
  };
}
